name: Pipeline de Testes Python

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      
    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Rodar os testes
      run: python -m unittest test_calculadora.py